import {MigrationInterface, QueryRunner} from "typeorm";

export class ProjectMigration1643289354184 implements MigrationInterface {
    name = 'ProjectMigration1643289354184'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "spatial_ref_sys" DROP CONSTRAINT "spatial_ref_sys_srid_check"`);
        await queryRunner.query(`CREATE TABLE "arquivo" ("id_arquivo" BIGSERIAL NOT NULL, "nome" text, "arquivo" bytea, CONSTRAINT "PK_623c36c7f5681b94d4967757fdd" PRIMARY KEY ("id_arquivo"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "arquivos_pkey" ON "arquivo" ("id_arquivo") `);
        await queryRunner.query(`CREATE TABLE "motivo_preservacao_arvore" ("id_motivo_preservacao" BIGSERIAL NOT NULL, "nome" character varying(100), CONSTRAINT "PK_df3690e8da745033b452ae693fa" PRIMARY KEY ("id_motivo_preservacao"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "motivo_preservacao_arvore_pkey" ON "motivo_preservacao_arvore" ("id_motivo_preservacao") `);
        await queryRunner.query(`CREATE TABLE "observacao_arvore" ("id_observacao" BIGSERIAL NOT NULL, "nome" character varying(30) NOT NULL, "preservar" boolean, CONSTRAINT "UQ_84f72f9a970d60f6af323c18bda" UNIQUE ("nome"), CONSTRAINT "PK_159a8af7ed725b69c5f9e5c31d7" PRIMARY KEY ("id_observacao"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "observacao_arvore_nome_unique" ON "observacao_arvore" ("nome") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "observacao_arvore_pkey" ON "observacao_arvore" ("id_observacao") `);
        await queryRunner.query(`CREATE TABLE "situacao_arvore" ("id_situacao" SERIAL NOT NULL, "nome" character varying(40) NOT NULL, CONSTRAINT "PK_9e0529000fbf7c21fe98412d499" PRIMARY KEY ("id_situacao"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "situacao_arvore_pkey" ON "situacao_arvore" ("id_situacao") `);
        await queryRunner.query(`CREATE TABLE "tipo_destino" ("id_tipo_destino" integer NOT NULL, "nome" character varying(50), CONSTRAINT "UQ_78ccf551224de33fdfa24e77d72" UNIQUE ("nome"), CONSTRAINT "PK_4860dc72d6730b208875886843d" PRIMARY KEY ("id_tipo_destino"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uk_pmlndrl7c6nqhn9ojguho3sp9" ON "tipo_destino" ("nome") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "tipo_destino_pkey" ON "tipo_destino" ("id_tipo_destino") `);
        await queryRunner.query(`CREATE TABLE "pessoa" ("id_pessoa" integer NOT NULL, "bairro" character varying(50), "cep" character varying(15), "cnf_cnpj" character varying(20), "endereco" character varying(50), "estado" character varying(50), "municipio" character varying(50), "nome" character varying(50), "numero" character varying(50), "pessoa_tipo" character varying(50), CONSTRAINT "PK_c0e02279074b76b486b56009ed4" PRIMARY KEY ("id_pessoa"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "pessoa_pkey" ON "pessoa" ("id_pessoa") `);
        await queryRunner.query(`CREATE TABLE "comprador" ("id_comprador" integer NOT NULL, "pessoa_id_pessoa" integer, CONSTRAINT "PK_d0cea252e7fb0069747fea4ce27" PRIMARY KEY ("id_comprador"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "comprador_pkey" ON "comprador" ("id_comprador") `);
        await queryRunner.query(`CREATE TABLE "tipo_motorista" ("id_tipo" bigint NOT NULL, "descricao" character varying(30), CONSTRAINT "PK_e13cbd2e63a57cfd3a00d6f7dfe" PRIMARY KEY ("id_tipo"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "tipo_motorista_pkey" ON "tipo_motorista" ("id_tipo") `);
        await queryRunner.query(`CREATE TABLE "motorista" ("id_motorista" BIGSERIAL NOT NULL, "nome" character varying(55), "endereco" character varying(250), "telefone" character varying(10), "celular" character varying(11), "habilitacao" character varying(20), "id_tipo" bigint, CONSTRAINT "PK_baf62c6f0b0877332f4ee5c6d7c" PRIMARY KEY ("id_motorista"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "motorista_pkey" ON "motorista" ("id_motorista") `);
        await queryRunner.query(`CREATE TABLE "situacao_poa" ("id_situacao" bigint NOT NULL, "situacao" character varying(21), CONSTRAINT "PK_f94f55f806f54d3452630342cdb" PRIMARY KEY ("id_situacao"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "situacao_poa_pkey" ON "situacao_poa" ("id_situacao") `);
        await queryRunner.query(`CREATE TABLE "poa" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "descricao" character varying(50), "data_ultimo_plan" character varying(50), "pmfs" character varying(50), "nome_resp_elab" character varying(50), "crea_resp_elab" character varying(25), "art_resp_elab" character varying(25), "nome_resp_exec" character varying(50), "crea_resp_exec" character varying(25), "art_resp_exec" character varying(25), "nome_detentor" character varying(50), "cpf_detentor" character varying(11), "nome_proponente" character varying(50), "cpf_proponente" character varying(11), "id_usuario" bigint, "corte_maximo" double precision(53), "id_parent" integer, "id_situacao" bigint, CONSTRAINT "PK_fea5005385ba39dd909110cbde1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "veiculo" ("id_veiculo" BIGSERIAL NOT NULL, "placa" character varying(8), "descricao" character varying(250), CONSTRAINT "PK_b44716b8e2c95dd609e14748ec2" PRIMARY KEY ("id_veiculo"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "caminhao_pkey" ON "veiculo" ("id_veiculo") `);
        await queryRunner.query(`CREATE TABLE "saida" ("id_saida" BIGSERIAL NOT NULL, "data_saida" date, "dof" character varying(40), "nf" character varying(40), "data_vencimento_dof" date, "agf" character varying(40), "data_vencimento_agf" date, "id_comprador" integer, "id_destino" bigint, "id_motorista" bigint, "id_poa" uuid, "id_veiculo" bigint, CONSTRAINT "PK_cca5a1737065d7a9ed5badf182f" PRIMARY KEY ("id_saida"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "saida_pkey" ON "saida" ("id_saida") `);
        await queryRunner.query(`CREATE TABLE "destino_tora" ("id_destino" BIGSERIAL NOT NULL, "descricao" character varying(40), "data_atualizacao" TIMESTAMP, "data_cadastro" TIMESTAMP, "nome" character varying(50), "id_tipo_destino" integer, CONSTRAINT "UQ_0369c93d81120b68a0106b72c25" UNIQUE ("nome"), CONSTRAINT "PK_cebc49279fb3f06400f4a1d6df4" PRIMARY KEY ("id_destino"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uk_jc1a8o2ukiaktxugqwmmtgv81" ON "destino_tora" ("nome") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "destino_tora_pkey" ON "destino_tora" ("id_destino") `);
        await queryRunner.query(`CREATE TABLE "tora" ("id_tora" BIGSERIAL NOT NULL, "patio" smallint, "sequencia" character varying(17) NOT NULL, "secao" character varying(3) NOT NULL, "diametro_tora_1" double precision(53), "diametro_tora_2" double precision(53), "diametro_tora_3" double precision(53), "diametro_tora_4" double precision(53), "diametro_oco_1" double precision(53), "diametro_oco_2" double precision(53), "diametro_oco_3" double precision(53), "diametro_oco_4" double precision(53), "comprimento_tora" double precision(53), "comprimento_oco" double precision(53), "volume_tora" double precision(53), "volume_oco" double precision(53), "data_digitacao" date, "tipo" smallint, "id_arvore" bigint, "id_destino" bigint, "id_saida" bigint, "id_ut" uuid, CONSTRAINT "PK_db6d32116d9c960120a14e6e310" PRIMARY KEY ("id_tora"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "tora_pkey" ON "tora" ("id_tora") `);
        await queryRunner.query(`CREATE TABLE "arvore" ("id_arvore" BIGSERIAL NOT NULL, "id_ut" uuid, "numero_arvore" integer, "dap" double precision(53), "altura" double precision(53), "fuste" integer, "area_basal" double precision(53), "volume" double precision(53), "comentario" character varying(100), "orient_x" character varying(1), "lat_x" double precision(53), "long_y" double precision(53), "faixa" integer, "gps" integer, "derrubada" boolean, "motivo_nao_derruba" character varying(120), "secoes" smallint, "id_substituida" bigint, "substituida" boolean, "ponto" smallint, "ponto_arvore" geometry, "arv_ponto" point, "lat" double precision(53), "lng" double precision(53), "id_especie" uuid, "id_motivo_preservacao" bigint, "id_observacao" bigint, "id_situacao" integer, CONSTRAINT "UQ_395870bcfb155829d6a1663d88a" UNIQUE ("id_ut"), CONSTRAINT "UQ_eb3d28b6b7a42b6fdc032f868e4" UNIQUE ("numero_arvore"), CONSTRAINT "PK_b2e6fc8c557b67f076d0128f7da" PRIMARY KEY ("id_arvore"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "arvore_ut_unique" ON "arvore" ("id_ut", "numero_arvore") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "inventario_pkey" ON "arvore" ("id_arvore") `);
        await queryRunner.query(`CREATE TABLE "categoria_especie_ut" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id_categoria" integer, "nome" character varying(100), "criterio_fuste" integer, "criterio_dminc" integer, "criterio_dmaxc" integer, "criterio_n_min_ut" integer, "criterio_perc_min_ut" integer, "preservar" boolean, "criterio_altura" integer, "criterio_volume" integer, CONSTRAINT "PK_4dd6330b360db8e5ced6160109e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "configuracoes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "modo_acesso" character varying(6), "endereco_host" character varying(15), "dap_min" smallint, "dap_max" smallint, "alt_min" smallint, "alt_max" smallint, "diam_min" smallint, "diam_max" smallint, "comp_min" smallint, "comp_max" smallint, CONSTRAINT "PK_7640d21fdc17722366904769d9e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "equacao_abasal" ("id_equacao" BIGSERIAL NOT NULL, "nome" character varying(50), "observacao" character varying(200), "expressao" character varying(1000), CONSTRAINT "PK_8e4b186fa1a0ebd2b168347c071" PRIMARY KEY ("id_equacao"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "equacao_abasal_equacao_pkey" ON "equacao_abasal" ("id_equacao") `);
        await queryRunner.query(`CREATE TABLE "equacao_modelo" ("equacao_modelo_id" BIGSERIAL NOT NULL, "expressao" character varying(1000), "nome" character varying(50), "tipo" integer, CONSTRAINT "PK_90456cb7e76d3ae4be0ab6f193c" PRIMARY KEY ("equacao_modelo_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "equacao_modelo_pkey" ON "equacao_modelo" ("equacao_modelo_id") `);
        await queryRunner.query(`CREATE TABLE "equacao_volume" ("id_equacao" BIGSERIAL NOT NULL, "nome" character varying(50), "observacao" character varying(200), "expressao" character varying(1000), CONSTRAINT "PK_d5f585e3aecafcdcfa39caad42b" PRIMARY KEY ("id_equacao"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "equacao_pkey" ON "equacao_volume" ("id_equacao") `);
        await queryRunner.query(`CREATE TABLE "parametro" ("id_parametro" integer NOT NULL, "codigo" character varying(255), "data_execucao" date, "descricao" character varying(50), "realizado" integer NOT NULL, "tipo_parametro" character varying(20), CONSTRAINT "UQ_98aa6d5f03731ea33310ac2a293" UNIQUE ("codigo"), CONSTRAINT "PK_03607d6c098a5e9598eeb615582" PRIMARY KEY ("id_parametro"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "parametro_pkey" ON "parametro" ("id_parametro") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uk_tfch6qwaswg8ho9n05wa36evf" ON "parametro" ("codigo") `);
        await queryRunner.query(`CREATE TABLE "status" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id_status" smallint, CONSTRAINT "PK_e12743a7086ec826733f54e1d95" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "teste_equacao" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "volume" double precision(53), "dap" double precision(53), "altura" double precision(53), "area_basal" double precision(53), CONSTRAINT "PK_097b9c56af06dbe9e3d97175123" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tipo_parametro" ("id_tipo_parametro" integer NOT NULL, "nome" character varying(50), CONSTRAINT "PK_1c1aba6dabae4b84f87c4bae220" PRIMARY KEY ("id_tipo_parametro"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "tipo_parametro_pkey" ON "tipo_parametro" ("id_tipo_parametro") `);
        await queryRunner.query(`CREATE TABLE "usuario" ("id_usuario" SERIAL NOT NULL, "nome" character varying(55), "login" character varying(15) NOT NULL, "senha" character varying(50) NOT NULL, "tipo" integer NOT NULL, "email" character varying(50), "cpf" character varying(50), CONSTRAINT "PK_dd52716c2652e0e23c15530c695" PRIMARY KEY ("id_usuario"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "usuario_pkey" ON "usuario" ("id_usuario") `);
        await queryRunner.query(`CREATE TABLE "versao" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "numero" character varying(5), CONSTRAINT "PK_4959fe47223dfeeddb1ef04d13b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "poa_categoria_especies_categoria_especie" ("poaId" uuid NOT NULL, "categoriaEspecieId" uuid NOT NULL, CONSTRAINT "PK_f739b11d427986fa9a154b8bc87" PRIMARY KEY ("poaId", "categoriaEspecieId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1076f2a62db6e2f8e69db479c3" ON "poa_categoria_especies_categoria_especie" ("poaId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d81efa20e10bca9938798bbd8c" ON "poa_categoria_especies_categoria_especie" ("categoriaEspecieId") `);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "ut" ADD "id_poa" uuid`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "description" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ut" ALTER COLUMN "origem" TYPE geometry`);
        await queryRunner.query(`CREATE UNIQUE INDEX "spatial_ref_sys_pkey" ON "spatial_ref_sys" ("srid") `);
        await queryRunner.query(`ALTER TABLE "comprador" ADD CONSTRAINT "FK_d37f8a719eba5b98e961ca94058" FOREIGN KEY ("pessoa_id_pessoa") REFERENCES "pessoa"("id_pessoa") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "motorista" ADD CONSTRAINT "FK_d2695062a22a83ed9e5c77058fb" FOREIGN KEY ("id_tipo") REFERENCES "tipo_motorista"("id_tipo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "poa" ADD CONSTRAINT "FK_912c8e1b3ed0f584dc30ccaa314" FOREIGN KEY ("id_situacao") REFERENCES "situacao_poa"("id_situacao") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saida" ADD CONSTRAINT "FK_a0dc76d971c29399a7b28e2bf72" FOREIGN KEY ("id_comprador") REFERENCES "comprador"("id_comprador") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saida" ADD CONSTRAINT "FK_aa80eb9eeee22866325fd380c05" FOREIGN KEY ("id_destino") REFERENCES "destino_tora"("id_destino") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saida" ADD CONSTRAINT "FK_1503a031fd9917212b14d337a5c" FOREIGN KEY ("id_motorista") REFERENCES "motorista"("id_motorista") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saida" ADD CONSTRAINT "FK_41879ba14626183e88e39f55994" FOREIGN KEY ("id_poa") REFERENCES "poa"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saida" ADD CONSTRAINT "FK_679ae34c9dc5073ace6bc9ced17" FOREIGN KEY ("id_veiculo") REFERENCES "veiculo"("id_veiculo") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "destino_tora" ADD CONSTRAINT "FK_4b2be95ef8ff65dc53a010742b2" FOREIGN KEY ("id_tipo_destino") REFERENCES "tipo_destino"("id_tipo_destino") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tora" ADD CONSTRAINT "FK_af3ba49743400171747b4b7a070" FOREIGN KEY ("id_arvore") REFERENCES "arvore"("id_arvore") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tora" ADD CONSTRAINT "FK_3fe8e9369b9b4c969bf0ab83732" FOREIGN KEY ("id_destino") REFERENCES "destino_tora"("id_destino") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tora" ADD CONSTRAINT "FK_04438b429350dc4b97f7cc03fe0" FOREIGN KEY ("id_saida") REFERENCES "saida"("id_saida") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tora" ADD CONSTRAINT "FK_37f9c913393cbd1310efdaedc08" FOREIGN KEY ("id_ut") REFERENCES "ut"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ut" ADD CONSTRAINT "FK_a851a2ad325ffe3204ac966de07" FOREIGN KEY ("id_poa") REFERENCES "poa"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "arvore" ADD CONSTRAINT "FK_f6576acbe81afc35b037d5efd12" FOREIGN KEY ("id_especie") REFERENCES "especie"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "arvore" ADD CONSTRAINT "FK_98a8d44195b6e0d27510753c648" FOREIGN KEY ("id_motivo_preservacao") REFERENCES "motivo_preservacao_arvore"("id_motivo_preservacao") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "arvore" ADD CONSTRAINT "FK_c4ecbea8b8ea3f7648efc038362" FOREIGN KEY ("id_observacao") REFERENCES "observacao_arvore"("id_observacao") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "arvore" ADD CONSTRAINT "FK_791ee5f2f23362979a3647e442b" FOREIGN KEY ("id_situacao") REFERENCES "situacao_arvore"("id_situacao") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "arvore" ADD CONSTRAINT "FK_395870bcfb155829d6a1663d88a" FOREIGN KEY ("id_ut") REFERENCES "ut"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "poa_categoria_especies_categoria_especie" ADD CONSTRAINT "FK_1076f2a62db6e2f8e69db479c37" FOREIGN KEY ("poaId") REFERENCES "poa"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "poa_categoria_especies_categoria_especie" ADD CONSTRAINT "FK_d81efa20e10bca9938798bbd8cc" FOREIGN KEY ("categoriaEspecieId") REFERENCES "categoria_especie"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "poa_categoria_especies_categoria_especie" DROP CONSTRAINT "FK_d81efa20e10bca9938798bbd8cc"`);
        await queryRunner.query(`ALTER TABLE "poa_categoria_especies_categoria_especie" DROP CONSTRAINT "FK_1076f2a62db6e2f8e69db479c37"`);
        await queryRunner.query(`ALTER TABLE "arvore" DROP CONSTRAINT "FK_395870bcfb155829d6a1663d88a"`);
        await queryRunner.query(`ALTER TABLE "arvore" DROP CONSTRAINT "FK_791ee5f2f23362979a3647e442b"`);
        await queryRunner.query(`ALTER TABLE "arvore" DROP CONSTRAINT "FK_c4ecbea8b8ea3f7648efc038362"`);
        await queryRunner.query(`ALTER TABLE "arvore" DROP CONSTRAINT "FK_98a8d44195b6e0d27510753c648"`);
        await queryRunner.query(`ALTER TABLE "arvore" DROP CONSTRAINT "FK_f6576acbe81afc35b037d5efd12"`);
        await queryRunner.query(`ALTER TABLE "ut" DROP CONSTRAINT "FK_a851a2ad325ffe3204ac966de07"`);
        await queryRunner.query(`ALTER TABLE "tora" DROP CONSTRAINT "FK_37f9c913393cbd1310efdaedc08"`);
        await queryRunner.query(`ALTER TABLE "tora" DROP CONSTRAINT "FK_04438b429350dc4b97f7cc03fe0"`);
        await queryRunner.query(`ALTER TABLE "tora" DROP CONSTRAINT "FK_3fe8e9369b9b4c969bf0ab83732"`);
        await queryRunner.query(`ALTER TABLE "tora" DROP CONSTRAINT "FK_af3ba49743400171747b4b7a070"`);
        await queryRunner.query(`ALTER TABLE "destino_tora" DROP CONSTRAINT "FK_4b2be95ef8ff65dc53a010742b2"`);
        await queryRunner.query(`ALTER TABLE "saida" DROP CONSTRAINT "FK_679ae34c9dc5073ace6bc9ced17"`);
        await queryRunner.query(`ALTER TABLE "saida" DROP CONSTRAINT "FK_41879ba14626183e88e39f55994"`);
        await queryRunner.query(`ALTER TABLE "saida" DROP CONSTRAINT "FK_1503a031fd9917212b14d337a5c"`);
        await queryRunner.query(`ALTER TABLE "saida" DROP CONSTRAINT "FK_aa80eb9eeee22866325fd380c05"`);
        await queryRunner.query(`ALTER TABLE "saida" DROP CONSTRAINT "FK_a0dc76d971c29399a7b28e2bf72"`);
        await queryRunner.query(`ALTER TABLE "poa" DROP CONSTRAINT "FK_912c8e1b3ed0f584dc30ccaa314"`);
        await queryRunner.query(`ALTER TABLE "motorista" DROP CONSTRAINT "FK_d2695062a22a83ed9e5c77058fb"`);
        await queryRunner.query(`ALTER TABLE "comprador" DROP CONSTRAINT "FK_d37f8a719eba5b98e961ca94058"`);
        await queryRunner.query(`DROP INDEX "public"."spatial_ref_sys_pkey"`);
        await queryRunner.query(`ALTER TABLE "ut" ALTER COLUMN "origem" TYPE geometry(GEOMETRY,0)`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "ut" DROP COLUMN "id_poa"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "description" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d81efa20e10bca9938798bbd8c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1076f2a62db6e2f8e69db479c3"`);
        await queryRunner.query(`DROP TABLE "poa_categoria_especies_categoria_especie"`);
        await queryRunner.query(`DROP TABLE "versao"`);
        await queryRunner.query(`DROP INDEX "public"."usuario_pkey"`);
        await queryRunner.query(`DROP TABLE "usuario"`);
        await queryRunner.query(`DROP INDEX "public"."tipo_parametro_pkey"`);
        await queryRunner.query(`DROP TABLE "tipo_parametro"`);
        await queryRunner.query(`DROP TABLE "teste_equacao"`);
        await queryRunner.query(`DROP TABLE "status"`);
        await queryRunner.query(`DROP INDEX "public"."uk_tfch6qwaswg8ho9n05wa36evf"`);
        await queryRunner.query(`DROP INDEX "public"."parametro_pkey"`);
        await queryRunner.query(`DROP TABLE "parametro"`);
        await queryRunner.query(`DROP INDEX "public"."equacao_pkey"`);
        await queryRunner.query(`DROP TABLE "equacao_volume"`);
        await queryRunner.query(`DROP INDEX "public"."equacao_modelo_pkey"`);
        await queryRunner.query(`DROP TABLE "equacao_modelo"`);
        await queryRunner.query(`DROP INDEX "public"."equacao_abasal_equacao_pkey"`);
        await queryRunner.query(`DROP TABLE "equacao_abasal"`);
        await queryRunner.query(`DROP TABLE "configuracoes"`);
        await queryRunner.query(`DROP TABLE "categoria_especie_ut"`);
        await queryRunner.query(`DROP INDEX "public"."inventario_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."arvore_ut_unique"`);
        await queryRunner.query(`DROP TABLE "arvore"`);
        await queryRunner.query(`DROP INDEX "public"."tora_pkey"`);
        await queryRunner.query(`DROP TABLE "tora"`);
        await queryRunner.query(`DROP INDEX "public"."destino_tora_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."uk_jc1a8o2ukiaktxugqwmmtgv81"`);
        await queryRunner.query(`DROP TABLE "destino_tora"`);
        await queryRunner.query(`DROP INDEX "public"."saida_pkey"`);
        await queryRunner.query(`DROP TABLE "saida"`);
        await queryRunner.query(`DROP INDEX "public"."caminhao_pkey"`);
        await queryRunner.query(`DROP TABLE "veiculo"`);
        await queryRunner.query(`DROP TABLE "poa"`);
        await queryRunner.query(`DROP INDEX "public"."situacao_poa_pkey"`);
        await queryRunner.query(`DROP TABLE "situacao_poa"`);
        await queryRunner.query(`DROP INDEX "public"."motorista_pkey"`);
        await queryRunner.query(`DROP TABLE "motorista"`);
        await queryRunner.query(`DROP INDEX "public"."tipo_motorista_pkey"`);
        await queryRunner.query(`DROP TABLE "tipo_motorista"`);
        await queryRunner.query(`DROP INDEX "public"."comprador_pkey"`);
        await queryRunner.query(`DROP TABLE "comprador"`);
        await queryRunner.query(`DROP INDEX "public"."pessoa_pkey"`);
        await queryRunner.query(`DROP TABLE "pessoa"`);
        await queryRunner.query(`DROP INDEX "public"."tipo_destino_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."uk_pmlndrl7c6nqhn9ojguho3sp9"`);
        await queryRunner.query(`DROP TABLE "tipo_destino"`);
        await queryRunner.query(`DROP INDEX "public"."situacao_arvore_pkey"`);
        await queryRunner.query(`DROP TABLE "situacao_arvore"`);
        await queryRunner.query(`DROP INDEX "public"."observacao_arvore_pkey"`);
        await queryRunner.query(`DROP INDEX "public"."observacao_arvore_nome_unique"`);
        await queryRunner.query(`DROP TABLE "observacao_arvore"`);
        await queryRunner.query(`DROP INDEX "public"."motivo_preservacao_arvore_pkey"`);
        await queryRunner.query(`DROP TABLE "motivo_preservacao_arvore"`);
        await queryRunner.query(`DROP INDEX "public"."arquivos_pkey"`);
        await queryRunner.query(`DROP TABLE "arquivo"`);
        await queryRunner.query(`ALTER TABLE "spatial_ref_sys" ADD CONSTRAINT "spatial_ref_sys_srid_check" CHECK (((srid > 0) AND (srid <= 998999)))`);
    }

}
